url: https://compilation.wordpress.com/
database:
  # the name of the JDBC driver, mysql in our case
  driverClass: com.mysql.jdbc.Driver
  # the username
  user: root
  #user: root
  # the password
  password: root1234@1234
  #password:
  # the JDBC URL; the database is called Dropwizard
  url: jdbc:mysql://localhost:3306/Dropwizard
  properties:
   charSet: UTF-8